### ISSUE TITLE
Add query to view all allowances for SNIP-20

### ISSUE THREAD

**Issue by baedrik** [SecretFoundation/SNIPs#4]
This is a request to add a key-authenticated query to the SNIP-20 spec, possibly called AllAllowances, that would take an address and a key as parameters and respond with a list of all non-zero allowances that address has authorized.

--Questions--
Should this query allow optional pagination?  Do we expect the average user to have set enough allowances that pagination would be useful?

Should this query also filter out expired allowances?  Because queries are performed locally, off-chain, there is no Env, so is checking whether the allowance has expired even feasible without access to an env.block.time?

**Comment by reuvenpo** [comment]
This has been discussed in the SNIP-23 specification discussion [here](https://github.com/SecretFoundation/SNIPs/pull/13#issuecomment-848655804), and we came to the conclusion that at least for now we don't want to include this feature.

I'm closing this issue for now, but let's open it again if a better design comes up.
